### 벡터와 행렬

In [80]:
import numpy as np

x = np.array([1,2,3])
type(x)
x.__class__

numpy.ndarray

In [81]:
x.shape

(3,)

In [87]:
x.ndim #1차원

1

### 2차원

In [85]:
W = np.array([[1,2,3],
             [4,5,6]])
W.shape

(2, 3)

In [88]:
W.ndim #2차원

2

### 행렬의 원소별 연산

In [89]:
W = np.array([[1,2,3],
             [4,5,6]])
X = np.array([[0,1,2],
             [3,4,5]])

W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [90]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

## 브로드캐스트
: 배열과 배열을 연산할때 잘 기억하기

In [92]:
A = np.array([[1,2],[3,4]])
A * 10 

array([[10, 20],
       [30, 40]])

In [94]:
A = np.array([[1,2],[3,4]])
b = np.array([10,20])
A * b

array([[10, 40],
       [30, 80]])

### 백터의 내적의 행렬의 곱 
dot

In [98]:
# 백터의 내적
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a.shape, b.shape)
print(np.dot(a,b)) 
print(a[0]*b[0] +a[1]*b[1]+ a[2]*b[2]) # 벡터의 내적 : 각 요소간의 곱의 합.

(3,) (3,)
32
32


In [99]:
# 행렬의 곱셉 : (m,n) * (n,l) = (m,l)
A = np.array([[1,2],
             [3,4]])
B = np.array([[5,6],
             [7,8]])
np.dot(A,B)

array([[19, 22],
       [43, 50]])